name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar o SDK Android
        run: |
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -P $HOME
          unzip -q $HOME/commandlinetools-linux-7583922_latest.zip -d $HOME/Android/Sdk/cmdline-tools/
          mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"
          echo "sdk.dir=$HOME/Android/Sdk" > $GITHUB_WORKSPACE/local.properties
          
      - name: Compilar o APK
        run: ./gradlew assembleDebug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
