name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Baixar e configurar SDK Android
        run: |
          mkdir -p $HOME/Android/Sdk
          cd $HOME/Android
          curl -o sdk-tools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip sdk-tools-linux.zip
          rm sdk-tools-linux.zip
          yes | ./cmdline-tools/bin/sdkmanager --licenses
          ./cmdline-tools/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Compilar o APK
        run: ./gradlew assembleDebug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-debug.apk
          path: ls -R app/build/outputs/apk/debug/app-debug.apk
