name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Baixar e configurar o SDK Android
        run: |
          mkdir -p $HOME/Android/Sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -P $HOME/Android/Sdk
          unzip $HOME/Android/Sdk/commandlinetools-linux-8512546_latest.zip -d $HOME/Android/Sdk
          $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      - name: Criar arquivo local.properties
        run: echo "sdk.dir=$HOME/Android/Sdk" > local.properties

      - name: Compilar o APK
        run: ./gradlew assembleDebug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
