name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar Android SDK
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8523003_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk
          rm commandlinetools.zip
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-34" "build-tools;34.0.0"
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk

      - name: Compilar o APK
        run: ./gradlew assembleDebug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
