name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configurar SDK Android
        uses: reactivecircus/android-sdk-action@v2
        with:
          api-level: 34
          build-tools: 34.0.0
          enable-cache: false

      - name: Compilar o APK
        run: ./gradlew assembleDebug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
